### ISSUE TITLE
doesn't work in node

### ISSUE THREAD

**Issue by richcollins** [Evilzebra/liquidfun-emscripten#1]
You need to add a module.exports = { b2Vec2: b2Vec2, ... } to liquidfun.js otherwise the properties aren't accessible after a require:

```
> console.log(require('liquidfun-emscripten').b2Vec2);
undefined
```

**Comment by Evilzebra** [comment]
After a long hiatus I am finally resolving some very overdue tasks. The [latest version (1.1.3)](https://github.com/Evilzebra/liquidfun-emscripten/releases/tag/1.1.3) has solved this issue with all `b2` functions and `b2_` variables being exported.
